// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh8goXaY2KwobtOz3i8vc1hc4jFMxZi04',
    appId: '1:629712858302:android:ef24b3bd8c18527d0282ef',
    messagingSenderId: '629712858302',
    projectId: 'bwi-cabswalle',
    storageBucket: 'bwi-cabswalle.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN51GRJRwTsIC85awJaOTpt8g_CJ6PAFY',
    appId: '1:629712858302:ios:72cd4fd3e61282090282ef',
    messagingSenderId: '629712858302',
    projectId: 'bwi-cabswalle',
    storageBucket: 'bwi-cabswalle.appspot.com',
    androidClientId: '629712858302-0s5nabe2qqh0pkdg8lp06rsvb75du187.apps.googleusercontent.com',
    iosBundleId: 'com.joy.cabswalle',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhFq05Tdld4OtkM4WxoCYGsPPUkCWLtK4',
    appId: '1:629712858302:web:24d6478c7eaf93d50282ef',
    messagingSenderId: '629712858302',
    projectId: 'bwi-cabswalle',
    authDomain: 'bwi-cabswalle.firebaseapp.com',
    storageBucket: 'bwi-cabswalle.appspot.com',
    measurementId: 'G-NSTH0YG0W2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN51GRJRwTsIC85awJaOTpt8g_CJ6PAFY',
    appId: '1:629712858302:ios:9618d64a6da6f0e60282ef',
    messagingSenderId: '629712858302',
    projectId: 'bwi-cabswalle',
    storageBucket: 'bwi-cabswalle.appspot.com',
    androidClientId: '629712858302-0s5nabe2qqh0pkdg8lp06rsvb75du187.apps.googleusercontent.com',
    iosBundleId: 'com.joy.cabswalle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9P-ZVdPiQCjozCOJ8EGsrLHnrmPi_uTs',
    appId: '1:629712858302:web:9ade97d9873158d80282ef',
    messagingSenderId: '629712858302',
    projectId: 'bwi-cabswalle',
    authDomain: 'bwi-cabswalle.firebaseapp.com',
    storageBucket: 'bwi-cabswalle.appspot.com',
    measurementId: 'G-K7HV3PQB6E',
  );

}